# This needs to be absolutely unique.
server-id: "SHIFT1"
redis:
  host: "localhost"
  port: 6379
  auth: "somes3curep4sswordh3re"
# time in minutes below...
Minimum players before game starts: 2
Time before games starts: '1:00'
Game time: '15:00'
Alpha Core block ID: 153
# The more messages, the more laggy it may be. (This is only after maybe thousands of possible messages, but just keep that in mind).
Death messages:
- "This faggot named PLAYER died by the master supreme god KILLER"
- "PLAYER you fucken gumpy shit. You died again."
- "Christ PLAYER, stop fucking dieing. God."
Spawns:
  tutorial_islandSpawnPoint:
    X: 1
    Y: 1
    Z: 1
    Pitch: 1
    Yaw: 1
  tutorial_staticPlatform:
    X: 1
    Y: 1
    Z: 1
    Pitch: 1
    Yaw: 1
  tutorial_alphacore:
    X: 1
    Y: 1
    Z: 1
    Pitch: 1
    Yaw: 1
  tutorial_enchantmentTable:
    X: 1
    Y: 1
    Z: 1
    Pitch: 1
    Yaw: 1
  tutorial_villagerSpawnPoint:
    X: 1
    Y: 1
    Z: 1
    Pitch: 1
    Yaw: 1
  tutorial_mainSpawnPoint:
    X: 1
    Y: 1
    Z: 1
    Pitch: 1
    Yaw: 1