name: ShiftSpawn
version: 1.6.2-BETA-SNAPSHOT
main: com.gmail.gogobebe2.shiftspawn.ShiftSpawn
description: The main plugin of the Shift minigame. Handles spawns, game logic, death events and more.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  shiftspawn:
    description: Set minigame spawns.
  test:
permissions:
  shiftspawn.*:
    default: op

depend: [XCore]
softdepend: [BungeeCord]
